### ISSUE TITLE
Item drawer using GUILayout.BeginArea and GUILayout.EndArea

### ISSUE THREAD

**Issue by rfadeev** [rotorz/unity3d-reorderable-list#1]
Custom item drawer works strange if it uses `GUILayout.BeginArea` and `GUILayout.EndArea` for the whole position of list item: item is not drawn until it's being dragged. I'm not sure whether it's a bug or an expected behaviour. Please see attached gif and example code for reference.

![guiareadrawer](https://user-images.githubusercontent.com/5451929/32498171-dc7a623a-c409-11e7-9873-5744caa7161b.gif)

**ItemDrawerEditorWindow.cs**
```
using System.Collections.Generic;
using UnityEngine;
using UnityEditor;
using Rotorz.Games.Collections;

public class ItemDrawerEditorWindow : EditorWindow
{
    public class Item
    {
        public string Id;
        public int Quantity;
    }

    private List<Item> items = new List<Item>();

    [MenuItem("Window/Item Drawer Editor Window")]
    private static void Init()
    {
        var window = EditorWindow.GetWindow(typeof(ItemDrawerEditorWindow));
        window.Show();
    }

    private void OnGUI()
    {
        EditorGUILayout.BeginVertical();

        ReorderableListGUI.Title("Items GUI Area Drawer");
        ReorderableListGUI.ListField(items, GUIAreaItemDrawer, DrawEmpty);

        ReorderableListGUI.Title("Items Id Drawer");
        ReorderableListGUI.ListField(items, ItemIdDrawer, DrawEmpty);

        EditorGUILayout.EndVertical();
    }

    private Item GUIAreaItemDrawer(Rect position, Item item)
    {
        if (item == null)
        {
            item = new Item();
        }

        GUILayout.BeginArea(position);

        EditorGUILayout.BeginHorizontal();

        item.Id = EditorGUILayout.TextField("Id", item.Id);
        item.Quantity = EditorGUILayout.IntField("Quantity", item.Quantity);

        EditorGUILayout.EndHorizontal();

        GUILayout.EndArea();

        return item;
    }

    private Item ItemIdDrawer(Rect position, Item item)
    {
        if (item == null)
        {
            item = new Item();
        }

        item.Id = EditorGUI.TextField(position, item.Id);
        return item;
    }

    private void DrawEmpty()
    {
        GUILayout.Label("No items in list.", EditorStyles.miniLabel);
    }
}
```

**Comment by kruncher** [comment]
I have a feeling that the problem is caused because of the following hierarchy is happening:
```
ReorderableListGUI.ListField (layout version)
|-- Draws list entries.
|    |-- GUILayout.BeginArea() (essentially making a nested layout system)
```

As mentioned in the Unity docs; [GUILayout.BeginArea](https://docs.unity3d.com/ScriptReference/GUILayout.BeginArea.html) cannot be nested. Whilst you are not explicitly nesting areas; I would hazard a guess that something similar is happening in this situation.

> This function is very useful when mixing GUILayout code. It must be matched with a call to EndArea. BeginArea / EndArea cannot be nested.

I have a hunch that the issue would not occur if you were to use the absolute version of `ReorderableListGUI.ListField(Rect, ...)`. In which case this is simply a limitation with Unity's layout system.

**Comment by rfadeev** [comment]
Many thanks for the answer!

>As mentioned in the Unity docs; [GUILayout.BeginArea](https://docs.unity3d.com/ScriptReference/GUILayout.BeginArea.html) cannot be nested. Whilst you are not explicitly nesting areas; I would hazard a guess that something similar is happening in this situation.

 `GUILayout.BeginArea` documentation is too vague. It does not specify what exactly is prohibited: putting several areas inside each other like
 ```
GUILayout.BeginArea(rectA);
GUILayout.BeginArea(rectB);
DrawSomething();
GUILayout.EndArea();
GUILayout.EndArea();
```
or whether it prohibits nesting area inside auto layout like
```
EditorGUILayout.BeginVertical();
GUILayout.BeginArea(position);
DrawSomething();
GUILayout.EndArea();
EditorGUILayout.EndVertical();
```
I've experimented a bit with nesting areas - both approaches above worked for me even with more complex nesting. Moreover, I do not see reordable list internal code using `GUILayout.BeginArea`.

>I have a hunch that the issue would not occur if you were to use the absolute version of `ReorderableListGUI.ListField(Rect, ...)`. In which case this is simply a limitation with Unity's layout system.

Using `ReorderableListGUI.ListFieldAbsolute` helps, but here is the problem - it requires `Rect` to be passed for drawing. I would like to avoid that. My use case is having laout version of editor drawer for item data (like `private void DrawItem(Item item)`) which is used heavily in my custom editor window in many places. I would like to reuse it in reordable list item drawer. Item can be pretty complex (several fields) and adding drawer just for reordable list feels wrong when I already have `DrawItem` drawer. Situation gets even worse when there are other `ItemA`, `ItemB` etc classes with corresponding `DrawItemA`, `DrawItemB` drawers and intend of putting `ItemA`, `ItemB` into reordable lists. All editor windows I implement use auto layout (i.e. `EditorGUILayout` calls).

Also this issue made me realized that there is a bit of contradiction in the current API. `ReorderableListGUI.ListField` seems to be designed as "auto layout" version of reordable list (and it does not require `Rect` arguement where to draw). But `ItemDrawer` drawer delegate requires position. So ideally for `ListField` to be fully "auto layout" delegate should not have `Rect` argument.

**Comment by kruncher** [comment]
> Moreover, I do not see reordable list internal code using GUILayout.BeginArea.

You are correct, the reordable list doesn't use `GUILayout.BeginArea` but effectively the same thing occurs. Attempting to have Unity create and maintain nested layout systems which it doesn't seem to like.

> But ItemDrawer drawer delegate requires position. So ideally for ListField to be fully "auto layout" delegate should not have Rect argument.

This is not a contradiction; the layout version of the list still draws the items with absolute positions. Pretty much for the same reasons that Unity's custom property drawers do.

By following Unity's advice and implementing the core custom control (the reorderable list) with absolute positions; it is easy to adapt the core control to work with Unity's layout system. Since it's adapted in this way, the items are drawn in the same way whether the outer control is drawn with automatic layout or without.

In order to fully support layout when within item drawers it would be necessary to define and maintain the entire library twice. Once implemented entirely with absolute layout `GUI` and once implemented entirely with automatic layout `GUILayout`. It should also be noted that the automatic layout version would perform poorly compared with the manually laid out version.

Realistically, in-order to support and maintain this cleanly Unity would need to enhance their layout system to support nested layouts. Not only would that help to address this issue it would help to address the very same issue in custom property drawers.

**Comment by rfadeev** [comment]
I'm wondering how Unity maintain two versions of their custom property drawers (and actually any other drawers which can be found in both `EditorGUI` and `EditorGUILayout`. If they call absolute version from auto layout one, then maybe it was wrong decision to make `DrawItem` implementations using auto layout.

> In order to fully support layout when within item drawers it would be necessary to define and maintain the entire library twice.

Completely understand you. The same I wanted to do - to use same item drawer instead of having two versions of it.

> It should also be noted that the automatic layout version would perform poorly compared with the manually laid out version.

Maybe I'm missing something, but I do not quite understand in which aspect it would perform poorly.

Still, thanks for all the explanations provided.

**Comment by kruncher** [comment]
> I'm wondering how Unity maintain two versions of their custom property drawers (and actually any other drawers which can be found in both EditorGUI and EditorGUILayout.

They don't. Custom property drawers can only be defined with absolute positions.

Their `EditorGUILayout.PropertyField` simply invokes the `EditorGUI.PropertyField` and both use manual layout. It would look something like this:

```csharp
public static void PropertyField(SerializedProperty property, GUIContent label, params GUILayoutOption options)
{
    Rect position = GUILayoutUtility.GetRect(0, EditorGUI.GetPropertyHeight(property), options);
    EditorGUI.PropertyField(position, property, label);
}
```

> Maybe I'm missing something, but I do not quite understand in which aspect it would perform poorly.

The layout system is way slower than just calculating the positions yourself and drawing them. For relatively small quantities of controls this isn't too much of an issue. But if you have a large quantity of controls (like a huge list of values) then the editor can become very slow.
